### PR TITLE
#4 Fix build failrure due to the use old 2.0 API - G2Engine.G2_ENTITY_SHOW_FEATURES_STATS

### PR DESCRIPTION
**Pull request by Hubbitus**
Fixes https://github.com/Senzing/senzing-listener/issues/4

### CODE REVIEW

**Comment by oskar700** [comment]
@Hubbitus Thank you for you contribution.
Please fill out an ICLA or CCLA (if applicable) and submit.  They can be found here:
https://github.com/Senzing/senzing-listener/tree/master/.github
The instructions are here:
https://github.com/Senzing/senzing-listener/blob/master/CONTRIBUTING.md
This is needed before I can merge the change.

**Comment by Hubbitus** [comment]
Ok: [senzing-individual-contributor-license-agreement-signed.pdf](https://github.com/Senzing/senzing-listener/files/5425324/senzing-individual-contributor-license-agreement-signed.pdf)

**Review by oskar700 — APPROVED** [review]
Thanks @Hubbitus

**Comment by Hubbitus** [comment]
Thank you

**Pull request merged**
